### PR TITLE
Update GrCM_plain.py syntax to yggdrasil names

### PR DESCRIPTION
**Pull request by langmm**
Yggdrasil uses different names for the interface (specifically cis is replaced with ygg)

### CODE REVIEW

**Comment by langmm** [comment]
I updated this PR to include your changes upstream, but I do not see an example data that should be read in for 'grn_input'. Can you add this data to the repo?

**Comment by kkavya03** [comment]
Input file for grn_input is './Input/GRN_Output.txt' in the 'GRN_Model' repository. I have mentioned this in 'GrCM_tofile.yml'. This data already exists in the repo. Is this what you are looking for?

**Comment by langmm** [comment]
Which file is it? I can't find anything with that name here: https://github.com/cropsinsilico/GRN_Model/tree/master/Input. It would be good to have a copy in this repository as well so we can run tests without installing the other repo.

**Comment by langmm** [comment]
Is it the GRN_Output.txt in the Output directory?

**Comment by langmm** [comment]
Nvm, will keep updating

**Comment by langmm** [comment]
So I was able to start trying to run, but lines 99-105 in GrCM_plain.py reference two fields in the data_static input that are not in the input table (namely "initial_protein_concEleMutant" and "initial_protein_concAmbMutant"). Should these be calculated somewhere or maybe the example input file is outdated?

These variables and the variables that reference them (r3 & r4 are not in the GrCM.py version).

**Comment by kkavya03** [comment]
GrCM_plain.py is the right version to be used. If you check the code again, first few lines of the code (line 70 to 82) create the columns "initial_protein_concEleMutant" and "initial_protein_concAmbMutant" in the static file in the source code itself. For creating these columns I also use columns from 'grn_input'. Is this the code you are running? - https://github.com/cropsinsilico/ProtTranslationModel_CO2/blob/master/src/GrCM_plain.py

**Comment by kkavya03** [comment]
Also,  '/GRN_Output.txt' is in the 'Output' directory of the GRN_Model repository -> './Output/GRN_Output.txt'. Apologize for the confusion

**Comment by kkavya03** [comment]
But GRN_Output.txt is also present in the 'Input' folder of ProtTranslationModel_CO2 repository for convenience with model integration with GrCM model

**Comment by langmm** [comment]
I am using GrCM_plain.py, but if you do a search for "initial_protein_concEleMutant" (and "initial_protein_concAmbMutant") it is only set as a variable, not a field in data_static. Should the field be set to the variable? Or should the variable be used instead of data_static["initial_protein_concEleMutant"] on line 98?

**Pull request merged**
